# Generated by Django 4.1 on 2022-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
